browse: guard against missing files
abrt on Fedora 20 reported a traceback:

	File "cola/models/browse.py", line 338, in date
	  st = core.stat(self.path)
	File "cola/core.py", line 186, in wrapped
	  return decorator(fn(action(*args, **kwargs)))
	OSError: [Errno 2] No such file or directory

This happens when a file is removed as we are gathering
modification times for display in the browser.

Catch the exception and recover gracefully.

Signed-off-by: David Aguilar <davvid@gmail.com>