sphinxtogithub: avoid unicode errors
When rebuilt against python-sphinx 1.2~b1+dfsg-1 (available in
experimental), git-cola failed to build from source:

	Exception occurred:
	File "extras/sphinxtogithub/sphinxtogithub.py", line 38, in process
	     return text.replace( self.from_, self.to )

	UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2
	in position 288: ordinal not in range(128)

The reason is that `path` is a bytes object.
Cast to str() to avoid the problem.

Signed-off-by: David Aguilar <davvid@gmail.com>