fsmonitor: fix mistyped fs_to_path_map variable
A typo was made in facfd5944b9c880e5b52066cbd8ee4e8ab9d0022 when the
wd_set variable was renamed to wd_to_path_map.  This code path
raises a NameError when inotify-watched files are removed from
the filesystem:

NameError: global name 'wd_to_path_set' is not defined

Closes #607
Reported-by: Joshua Taylor <joshuataylorx@gmail.com>
Signed-off-by: David Aguilar <davvid@gmail.com>