browse: handle object deletion when paths are untracked
If an existing path becomes untracked git-cola would try to send a
signal to a dead C++ object and crash:

	RuntimeError: wrapped C/C++ object of type
	              GitRepoNameItem has been deleted
	error: git-cola died of signal 6

Disconnect signals when connecting to the global GitRepoEntry instances
so that no signals are ever delivered to deleted objects.

Signed-off-by: David Aguilar <davvid@gmail.com>