gitcmds: guard against missing HEAD
Disable the stat cache when .git/HEAD is missing.
This avoids the following error:

UnboundLocalError: local variable 'key' referenced before assignment

The fix for the Fedora bugreport was in v1.9.2 via
1d2d7e149639ca4414989e5f563561b6c57b42ea where we stripped off
newlines.  This edge case remained, though technically we'll
never hit it.

C.f. https://bugzilla.redhat.com/show_bug.cgi?id=1036405

Signed-off-by: David Aguilar <davvid@gmail.com>