po/pt_BR.po: fix po syntax, fixes #319
Commit 19c57b94 introduces translation with missing/additional double-
quotes and causes build error
````
msgfmt -o share/locale/pt_BR/LC_MESSAGES/git-cola.mo po/pt_BR.po
po/pt_BR.po:294: end-of-line within string
po/pt_BR.po:386:11: syntax error
msgfmt: found 2 fatal errors
error: command 'msgfmt' failed with exit status 1
make: *** [all] Error 1
````
This commit fixes the syntax.

Signed-off-by: Ｖ字龍(Vdragon) <Vdragon.Taiwan@gmail.com>